[language-server.typos]
command = "typos-lsp"

[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "copilot", "--copilotApiKey", "private_key"]

[language-server.clangd]
command = "clangd"
args = [
    "--clang-tidy",
    "--fallback-style=none"
]

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi"]
language-servers = [ "pyright", "ruff", "typos", "gpt" ]
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "cpp", "c++", "hpp", "h"]
language-servers = [ "clangd", "typos", "gpt" ]
auto-format = true
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "clang-format" }
# args = ["-style={BasedOnStyle: Google, IndentWidth: 4, TabWidth: 4, UseTab: Always, ColumnLimit: 100, Standard: Latest, AccessModifierOffset: -4}"]

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "clangd", "typos", "gpt" ]
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "clang-format" }
# args = ["-style={BasedOnStyle: Google, IndentWidth: 4, TabWidth: 4, UseTab: Always, ColumnLimit: 100, Standard: Latest}"]
auto-format = true
