# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=20000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/horikita/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

if [[ -z $DISPLAY ]] && [[ $(tty) == /dev/tty1 ]]; then
    exec Hyprland
fi


# Lines generated by chatgpt for making the cursor regular when in write mode:
# -----------------------------------------------------------------------------
# Function to set cursor shape (1 = block, 3 = blinking underline, 5 = blinking bar)
function zle-keymap-select {
  if [[ $KEYMAP == vicmd ]]; then
    echo -ne '\e[1 q'  # block cursor for normal mode
  else
    echo -ne '\e[5 q'  # bar cursor for insert mode
  fi
}
zle -N zle-keymap-select

# Also trigger on line init
function zle-line-init {
  zle-keymap-select
}
zle -N zle-line-init

# Make sure terminal resets cursor on exit
function zle-line-finish {
  echo -ne '\e[5 q'
}
zle -N zle-line-finish
# -----------------------------------------------------------------------------

function git_branch_name()
{
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
    echo '%F{yellow}<'$branch'>%f '
  fi
}
# Enable substitution in the prompt.
setopt prompt_subst

PROMPT='%F{blue}%~%f $(git_branch_name)$ '


# Colors:
export TERM="xterm-256color"
export COLORTERM=truecolor

# Editor:
export EDITOR='nvim'
export VISUAL='nvim'

# Plugins:
source $HOME/.antidote/antidote.zsh
antidote load

# Keybinds:
bindkey "^K" history-substring-search-up
bindkey "^J" history-substring-search-down

# Aliases:
alias ls="exa"
alias ll="exa -alh"
alias tree="exa --tree"
alias python="python3"
alias rcat="/bin/cat"
alias cat='bat'
alias vim='nvim'
alias qemu='qemu-system-x86_64'
eval "$(zoxide init --cmd cd zsh)"
eval "$(fzf --zsh)"


# Path:
export PATH=$PATH:~/snap
