# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=20000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/horikita/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall




# Lines generated by chatgpt for making the cursor regular when in write mode:
# -----------------------------------------------------------------------------
# Function to set cursor shape (1 = block, 3 = blinking underline, 5 = blinking bar)
function zle-keymap-select {
  if [[ $KEYMAP == vicmd ]]; then
    echo -ne '\e[1 q'  # block cursor for normal mode
  else
    echo -ne '\e[5 q'  # bar cursor for insert mode
  fi
}
zle -N zle-keymap-select

# Also trigger on line init
function zle-line-init {
  zle-keymap-select
}
zle -N zle-line-init

# Make sure terminal resets cursor on exit
function zle-line-finish {
  echo -ne '\e[5 q'
}
zle -N zle-line-finish
# -----------------------------------------------------------------------------




# Making it so it will show what dir you are in:
PROMPT='%F{blue}%~ %f$ '

# sourceing things:
export TERM="xterm-256color"
export COLORTERM=truecolor

# aliases:
alias ll="ls -al"
alias python="python3"
